// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EmailApp.Models;

public partial class Email
{
    public int EmailId { get; set; }

    [Required, EmailAddress]
    public string FromEmail { get; set; }

    [Required, EmailAddress]
    public string ToEmail { get; set; }

    public string CcEmails { get; set; }

    [Required]
    public string Subject { get; set; }

    [Required]
    public string Importance { get; set; } = "Normal";

    [Required]
    public string Content { get; set; }

    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;
}