// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EmailApp.Validation;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EmailApp.Models;

public partial class Email
{
    public int EmailId { get; set; }

    [Required]
    [CustomEmail]
    public string FromEmail { get; set; }

    [Required, EmailAddress]
    public string ToEmail { get; set; }

    [MultipleEmailAddresses]
    public string CcEmails { get; set; }

    [Required]
    [StringLength(100, ErrorMessage = "Subject length can't be more than 100 characters.")]
    public string Subject { get; set; }

    [Required]
    public string Importance { get; set; } = "Normal";

    [Required]
    [StringLength(1000, ErrorMessage = "Content length can't be more than 1000 characters.")]
    public string Content { get; set; }

    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;
}