// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmailApp.Models;

public partial class Email
{
    public int EmailId { get; set; }

    public string FromEmail { get; set; }

    public string ToEmail { get; set; }

    public string CcEmails { get; set; }

    public string Subject { get; set; }

    public byte Importance { get; set; }

    public string Content { get; set; }

    public DateTime Created { get; set; }
}